-- 人ごとのAIエージェント用APIキー発行機能 (WIPAPPDEV-000100)
--
-- 背景: X-AI-Api-Key は従来、全社共有の1本のキーのみで、常に固定の共有アカウント(ai_agent)として
-- 動作していた。本マイグレーションでは、人ごとにAPIキーを発行できるようにし、AIエージェント経由の
-- 操作について実際の実行者(acting_user)を記録できるようにする。
--
-- 平文キーはどの列にも保存しない。SHA-256ハッシュ(key_hash)のみ保存し、認証時はハッシュの
-- 完全一致検索で照合する(高エントロピーなランダムトークンが前提のため、bcrypt/argon2のような
-- 低速化ハッシュではなく、O(1)検索が可能な決定的ハッシュを採用する)。

CREATE TABLE ai_agent_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE,
    key_hash TEXT NOT NULL UNIQUE,
    key_prefix TEXT NOT NULL,
    label TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ NULL,
    revoked_at TIMESTAMPTZ NULL,
    created_by BIGINT NULL REFERENCES accounts_user(id) ON DELETE SET NULL
);

CREATE INDEX idx_ai_agent_api_keys_user_id ON ai_agent_api_keys (user_id);

-- AIエージェント経由(人ごとキー認証成功時)で投稿されたコメントの実際の実行者。
-- 人間の通常投稿・共有キー経由の投稿では常にNULL。
ALTER TABLE tickets_comment
    ADD COLUMN ai_agent_acting_user_id BIGINT NULL REFERENCES accounts_user(id) ON DELETE SET NULL;
