-- チケット詳細リアクション (WIPAPPDEV-000087 Phase 0)

-- リアクション: ユーザーがチケットに付与する Unicode / カスタム絵文字
CREATE TABLE public.tickets_reaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL REFERENCES public.tickets_ticket(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE,
  emoji_kind text NOT NULL CHECK (emoji_kind IN ('unicode', 'custom')),
  emoji_value text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (ticket_id, user_id, emoji_kind, emoji_value)
);
CREATE INDEX idx_tickets_reaction_ticket ON public.tickets_reaction (ticket_id);

-- カスタム絵文字: プロジェクト単位でアップロード可能
CREATE TABLE public.tickets_custom_emoji (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.tickets_project(id) ON DELETE CASCADE,
  slug text NOT NULL,
  name text NOT NULL,
  image_path text NOT NULL,
  uploaded_by bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (project_id, slug)
);
CREATE INDEX idx_tickets_custom_emoji_project ON public.tickets_custom_emoji (project_id);

-- アーカイブチームガード: tickets_reaction に via_ticket トリガーを適用
DROP TRIGGER IF EXISTS trg_guard_archived_team_reaction ON tickets_reaction;
CREATE TRIGGER trg_guard_archived_team_reaction
    BEFORE INSERT OR UPDATE OR DELETE ON tickets_reaction
    FOR EACH ROW EXECUTE FUNCTION guard_archived_team_via_ticket();
