CREATE TABLE IF NOT EXISTS public.tickets_comment_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES public.tickets_comment(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    UNIQUE (comment_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_tickets_comment_subscription_comment_id
    ON public.tickets_comment_subscription (comment_id);
CREATE INDEX IF NOT EXISTS idx_tickets_comment_subscription_user_id
    ON public.tickets_comment_subscription (user_id);

COMMENT ON TABLE public.tickets_comment_subscription IS
    'コメントスレッド(トップレベルコメント単位)の購読。comment_idは常にparent_comment_id IS NULLのコメントを指す(アプリケーション層で保証)。';
