-- Step A: Create tickets_project_teams table
CREATE TABLE tickets_project_teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL
        REFERENCES tickets_project(id) ON DELETE CASCADE,
    team_id bigint NOT NULL
        REFERENCES m_team(id) ON DELETE CASCADE,
    joined_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_project_team UNIQUE (project_id, team_id)
);

CREATE INDEX idx_project_teams_team ON tickets_project_teams (team_id);
CREATE INDEX idx_project_teams_project ON tickets_project_teams (project_id);

-- Step B: Backfill from existing owner_team_id
INSERT INTO tickets_project_teams (project_id, team_id, joined_at)
SELECT p.id, p.owner_team_id, COALESCE(p.created_at, NOW())
FROM tickets_project p
WHERE p.owner_team_id IS NOT NULL
ON CONFLICT (project_id, team_id) DO NOTHING;

-- Step C: Rescue projects without owner_team_id from ticket team_ids
INSERT INTO tickets_project_teams (project_id, team_id, joined_at)
SELECT DISTINCT t.project_id, t.team_id, NOW()
FROM tickets_ticket t
WHERE t.project_id IS NOT NULL
  AND t.team_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM tickets_project_teams pt
      WHERE pt.project_id = t.project_id
  )
ON CONFLICT (project_id, team_id) DO NOTHING;

-- Step C2: Fail loudly if any project still has zero participating teams
DO $$
DECLARE
  orphan_count bigint;
BEGIN
  SELECT COUNT(*) INTO orphan_count
  FROM tickets_project p
  WHERE NOT EXISTS (
    SELECT 1 FROM tickets_project_teams pt WHERE pt.project_id = p.id
  );
  IF orphan_count > 0 THEN
    RAISE EXCEPTION
      'project_team_nm: % project(s) still have zero participating teams after backfill',
      orphan_count;
  END IF;
END $$;

-- Step D: Fix tickets with team_id not in project's participating teams
-- Strategy: Set team_id to the minimum team_id in the project's participating teams
UPDATE tickets_ticket t
SET team_id = sub.team_id
FROM (
    SELECT DISTINCT ON (pt.project_id)
        pt.project_id, pt.team_id
    FROM tickets_project_teams pt
    ORDER BY pt.project_id, pt.team_id
) sub
WHERE t.project_id = sub.project_id
  AND t.team_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM tickets_project_teams pt2
      WHERE pt2.project_id = t.project_id AND pt2.team_id = t.team_id
  );

-- Step E: Create trigger to enforce team participation constraint
CREATE OR REPLACE FUNCTION check_ticket_team_in_project_teams()
RETURNS trigger AS $$
BEGIN
  IF NEW.project_id IS NULL THEN
    RETURN NEW;  -- Team-only tickets are not constrained
  END IF;
  IF NEW.team_id IS NULL THEN
    RAISE EXCEPTION 'project-attached ticket requires team_id';
  END IF;
  IF NOT EXISTS (
      SELECT 1 FROM tickets_project_teams
      WHERE project_id = NEW.project_id AND team_id = NEW.team_id
  ) THEN
    RAISE EXCEPTION 'team_id=% is not a participant of project_id=%',
      NEW.team_id, NEW.project_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ticket_team_in_project_teams
  BEFORE INSERT OR UPDATE OF project_id, team_id ON tickets_ticket
  FOR EACH ROW EXECUTE FUNCTION check_ticket_team_in_project_teams();

-- Step F: Drop owner_team_id constraint and column
-- Drop existing constraint and index (if they exist)
ALTER TABLE tickets_project
  DROP CONSTRAINT IF EXISTS tickets_project_owner_team_id_6b66cf67_fk_m_team_id;

DROP INDEX IF EXISTS tickets_project_owner_team_id_6b66cf67;

-- Drop the column
ALTER TABLE tickets_project DROP COLUMN owner_team_id;

-- Step G: Validation queries
-- This comment block contains the validation queries to be run after migration:
-- SELECT COUNT(*) FROM tickets_project p
-- WHERE NOT EXISTS (
--   SELECT 1 FROM tickets_project_teams pt WHERE pt.project_id = p.id
-- );
--
-- SELECT COUNT(*) FROM tickets_ticket t
-- WHERE t.project_id IS NOT NULL
--   AND (
--     t.team_id IS NULL
--     OR NOT EXISTS (
--       SELECT 1 FROM tickets_project_teams pt
--       WHERE pt.project_id = t.project_id AND pt.team_id = t.team_id
--     )
--   );
