CREATE TABLE IF NOT EXISTS public.tickets_ticket_reviewers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticketmodel_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS tickets_ticket_reviewers_ticketmodel_id_a1ab7f28 ON public.tickets_ticket_reviewers USING btree (ticketmodel_id);
CREATE INDEX IF NOT EXISTS tickets_ticket_reviewers_user_id_1495e909 ON public.tickets_ticket_reviewers USING btree (user_id);

DO $$ BEGIN
    ALTER TABLE ONLY public.tickets_ticket_reviewers
    ADD CONSTRAINT tickets_ticket_reviewers_ticketmodel_id_user_id_488ca910_uniq UNIQUE (ticketmodel_id, user_id);
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE ONLY public.tickets_ticket_reviewers
    ADD CONSTRAINT tickets_ticket_reviewers_ticketmodel_id_a1ab7f28_fk_tickets_t FOREIGN KEY (ticketmodel_id) REFERENCES public.tickets_ticket(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE ONLY public.tickets_ticket_reviewers
    ADD CONSTRAINT tickets_ticket_reviewers_user_id_1495e909_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL;
END $$;
