-- パスワードリセット用ワンタイムトークン
CREATE TABLE IF NOT EXISTS public.auth_password_reset_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token character varying(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT auth_password_reset_token_token_key UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS auth_password_reset_token_user_active_idx
    ON public.auth_password_reset_token (user_id)
    WHERE used_at IS NULL;
