CREATE TABLE IF NOT EXISTS public.ticket_link (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL REFERENCES public.tickets_ticket(id) ON DELETE CASCADE,
    url character varying(2048) NOT NULL,
    title character varying(255),
    created_by_id bigint NOT NULL REFERENCES public.accounts_user(id),
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ticket_link_ticket_id ON public.ticket_link (ticket_id);
