CREATE TABLE IF NOT EXISTS public.wiki_attachment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wiki_page_id bigint NOT NULL REFERENCES public.wiki_page(id) ON DELETE CASCADE,
    filename character varying(255) NOT NULL,
    file character varying(255) NOT NULL,
    file_size integer NOT NULL,
    uploader_id bigint NOT NULL REFERENCES public.accounts_user(id),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT wiki_attachment_file_size_check CHECK ((file_size >= 0))
);

CREATE INDEX IF NOT EXISTS idx_wiki_attachment_wiki_page_id ON public.wiki_attachment (wiki_page_id);
